language: node_js
node_js:
  - "node"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_install:
  - if [ `uname` = "Linux" ]; then export CXX=g++-4.9; fi

install:
  - npm install
script:
  - npm test
